name = "Vehicle Queue"
max_fleets = 4

[fleets.3]
building_prerequisites={gargage=12}
costs={food=1000000,oil=1000000}


[fleets.4]
building_prerequisites={garage=19}
costs={food=4000000,oil=4000000,steel=1000000}
