name = "Training Grounds"
description = ""
max_level = 30
effects = ["max_recruitment", "recruitment_speedup"]


[levels.10]
  max_recruitment = 50
  recruitment_speedup = 0.025
  battle_power = 625
  building_prerequisites={main-hall=10}
  costs={food=11940,oil=27870}
  gold_cost=190
  duration="1h 14m 43s"

[levels.11]
  max_recruitment = 55
  recruitment_speedup = 0.03
  battle_power = 625
  building_prerequisites={main-hall=11}
  costs={food=24180,oil=56420}
  gold_cost=258
  duration="1h 41m 25s"

[levels.14]
  max_recruitment = 70
  recruitment_speedup = 0.035
  # battle_power = 625
  building_prerequisites={main-hall=14}
  costs={food=98540,oil=229940}
  gold_cost=548
  duration="3h 37m 33s"
